function Hd = filtroFIR_2
%FILTROFIR_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 16-May-2015 22:19:53

% Numerator coefficient vector
Numerator = [-0.008 0.064 0.443 0.443 0.064 -0.008];

Hd = dsp.FIRFilter( ...
    'Numerator', Numerator);

% [EOF]
