function y = untitled(x)
%UNTITLED Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 18-May-2015 15:10:17

persistent Hd;

if isempty(Hd)
    
    Fpass = 0.45;  % Passband Frequency
    Fstop = 0.55;  % Stopband Frequency
    Apass = 1;     % Passband Ripple (dB)
    Astop = 60;    % Stopband Attenuation (dB)
    
    h = fdesign.rsrc(2, 3, 'Lowpass', 'fp,fst,ap,ast', Fpass, Fstop, Apass, ...
        Astop);
    
    Hd = design(h, 'kaiserwin');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


